# Generated by Django 5.1 on 2024-10-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_player_full_name_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('username', 'email')},
        ),
        migrations.AlterModelTable(
            name='player',
            table='player_table',
        ),
    ]
