# Generated by Django 5.1 on 2024-11-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_player_options_alter_player_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
