# Generated by Django 5.1 on 2024-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_player_managers_player_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
