# Generated by Django 5.1 on 2024-12-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_player_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='last_login',
        ),
        migrations.AlterModelTable(
            name='player',
            table='transcendence_player',
        ),
    ]
