# Generated by Django 5.1 on 2024-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_player_last_login_alter_player_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
