# Generated by Django 5.1 on 2024-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_player_blocked_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='blocked_users',
            new_name='blocked_players',
        ),
    ]
