# Generated by Django 5.1 on 2024-12-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_blocked_users_player_blocked_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_password_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
