# Generated by Django 5.1 on 2025-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_player_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_42_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.BigIntegerField(default=0),
        ),
    ]
