# Generated by Django 5.1 on 2024-10-05 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(db_column='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(db_column='is_staff', default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_login',
            field=models.DateTimeField(db_column='last_login', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(db_column='password', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='secret',
            field=models.CharField(blank=True, db_column='secret', max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='tfa',
            field=models.BooleanField(db_column='tfa', default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(db_column='username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='verified',
            field=models.BooleanField(db_column='verified', default=False),
        ),
    ]
