# Generated by Django 5.1 on 2024-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tfa',
            field=models.BooleanField(default=False),
        ),
    ]
