# Generated by Django 5.1 on 2024-10-11 00:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_player_date_joined_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[app.models.validate_image_size]),
        ),
    ]
