# Generated by Django 5.1 on 2024-09-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_player_id_alter_player_username_twofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='secret',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='player',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
