# Generated by Django 5.1 on 2024-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bloguser_first_name_alter_bloguser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
