# Generated by Django 5.1 on 2024-10-13 07:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pics/', validators=[app.models.validate_image_size]),
        ),
    ]
