# Generated by Django 5.1 on 2024-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
