# Generated by Django 5.1 on 2024-12-14 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_two', models.CharField(default='Dummy', max_length=100)),
                ('game_time', models.DateTimeField(auto_now_add=True)),
                ('game_type', models.CharField(choices=[('AI', 'Against AI'), ('LOCAL', 'Locally Played'), ('TOURNAMENT', 'Played in Tournament')], max_length=20)),
                ('game_score', models.CharField(blank=True, max_length=20, null=True)),
                ('game_outcome', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_table',
                'ordering': ['-game_time'],
            },
        ),
    ]
