# Generated by Django 5.1 on 2024-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_outcome',
            field=models.CharField(choices=[('STARTED', 'Game Started'), ('WIN', 'You Won'), ('LOSS', 'You Loss'), ('CANCELLED', 'Game Cancelled')], default='STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_score',
            field=models.CharField(default='0-0', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('AI', 'Against AI'), ('LOCAL', 'Locally Played'), ('TOURNAMENT', 'Played in Tournament')], default='LOCAL', max_length=20),
        ),
    ]
