# Generated by Django 5.1 on 2024-12-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_outcome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id']},
        ),
    ]
