# Generated by Django 5.1 on 2025-01-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(choices=[('STARTED', 'Game Started'), ('WIN', 'You Won'), ('LOSE', 'You Lost'), ('CANCELLED', 'Game Cancelled')], default='CANCELLED', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_one',
            field=models.CharField(default='player_one', max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_two',
            field=models.CharField(default='player_two', max_length=100),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=4)),
                ('games', models.ManyToManyField(to='game.game')),
            ],
            options={
                'db_table': 'tournament_table',
                'ordering': ['id'],
            },
        ),
    ]
