# Generated by Django 5.1 on 2024-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(default='NULL', max_length=150),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(default='NULL', max_length=150),
        ),
    ]
