# Generated by Django 5.1 on 2024-08-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bloguser_first_name_bloguser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='last_name',
        ),
    ]
