# Generated by Django 5.1 on 2024-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bloguser_first_name_alter_bloguser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
