# Generated by Django 5.1 on 2024-12-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_blockedplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedPlayer',
        ),
    ]
