# Generated by Django 5.1 on 2024-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_blockedplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='blocker_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
