# Generated by Django 5.1 on 2024-12-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_blocker_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='blocker_username',
        ),
    ]
