# Generated by Django 5.1 on 2024-12-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_conversed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='conversed_at',
        ),
    ]
