# Generated by Django 5.1 on 2024-12-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatroom_conversed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='conversed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
