# Generated by Django 5.1 on 2024-10-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_alter_friendlist_table_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
