# Generated by Django 5.1 on 2024-11-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
