# Generated by Django 5.1 on 2024-12-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications_table',
        ),
    ]
