# Generated by Django 5.1 on 2024-12-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0008_notification_read_status_alter_notification_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
