# Generated by Django 5.1 on 2024-12-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0012_alter_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_pfp_url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
