# Generated by Django 5.1 on 2024-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0014_alter_notification_sender_pfp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_pfp_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
