# Generated by Django 5.1 on 2024-12-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0016_remove_notification_sender_pfp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_username',
        ),
    ]
